### ISSUE TITLE
E/Vold    (   52): Unable to open /dev/block/loop0 (No such device or address)

### ISSUE THREAD

**Issue by mjedrasik** [loxK/android_device_htc_hero#21] opened 2010-07-05 11:19 UTC
Happens on installing Google Sky Map, it fails.

Logcat below.

I/ActivityManager(   94): Displayed activity com.google.android.gm/.ConversationListActivity: 34947 ms (total 34947 ms)
D/NativeCrypto(  384): Freeing OpenSSL session
D/dalvikvm(  384): GC_EXPLICIT freed 4726 objects / 305240 bytes in 239ms
W/InputManagerService(   94): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@43dea9f0
W/InputManagerService(   94): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@43de30b8
I/ActivityManager(   94): Starting activity: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.android.vending/.AssetBrowserActivity bnds=[243,238][317,317] }
D/dalvikvm( 3395): GC_EXPLICIT freed 5014 objects / 244176 bytes in 712ms
D/dalvikvm(  552): GC_EXPLICIT freed 127 objects / 6056 bytes in 108ms
D/dalvikvm(   94): GC_FOR_MALLOC freed 15332 objects / 1242824 bytes in 197ms
I/Gmail   ( 3395): MainSyncRequestProto: lowestBkwdConvoId: 0, highestHandledServerOp: 35430, normalSync: true
I/ActivityManager(   94): Starting activity: Intent { act=android.intent.action.VIEW cmp=com.android.vending/.AssetPermissionsSubActivity (has extras) }
I/ActivityManager(   94): Displayed activity com.android.vending/.AssetPermissionsSubActivity: 616 ms (total 616 ms)
D/dalvikvm( 3395): GC_EXPLICIT freed 5106 objects / 190824 bytes in 89ms
I/Gmail   ( 3395): MainSyncRequestProto: lowestBkwdConvoId: 0, highestHandledServerOp: 35431, normalSync: true
D/vending (  542): [237] LocalAssetDatabase.notifyListener(): 5972884208432727470 / DOWNLOAD_PENDING
I/vending (  542): [237] RequestDispatcher$RequestContext.<init>(): Some requests use secure token but dont require SSL. Forcing SSL.
D/vending (  542): [263] AssetDownloader.downloadAndInstall(): Initiating Download for 1 applications.
I/vending (  542): [263] DownloadManagerUtil.enqueueDownload(): Enqueue for download com.android.vending.util.DownloadManagerUtil$Request@43f0c298
D/vending (  542): [263] LocalAssetDatabase.notifyListener(): 5972884208432727470 / null
D/vending (  542): [263] LocalAssetDatabase.notifyListener(): 5972884208432727470 / DOWNLOADING
I/Gmail   ( 3395): MainSyncRequestProto: lowestBkwdConvoId: 0, highestHandledServerOp: 35431, normalSync: true
D/dalvikvm( 3395): GC_EXPLICIT freed 2142 objects / 92056 bytes in 97ms
I/Gmail   ( 3395): MainSyncRequestProto: lowestBkwdConvoId: 0, highestHandledServerOp: 35431, normalSync: true
D/dalvikvm(  384): GC_FOR_MALLOC freed 7634 objects / 404680 bytes in 184ms
D/NativeCrypto(  542): Freeing OpenSSL session
D/dalvikvm(  542): GC_EXPLICIT freed 13029 objects / 815392 bytes in 199ms
I/vending (  542): [264] AssetDownloader$DownloadManagerBroadcastReceiver.startNextDownload(): Found Paused URI null
I/vending (  542): [264] AssetDownloader$DownloadManagerBroadcastReceiver.startNextDownload(): No more paused downloads.
D/vending (  542): [264] AssetDownloader$DownloadManagerBroadcastReceiver.handleDownloadCompletedAction(): Got a download completed intent.
D/vending (  542): [264] LocalAssetDatabase.notifyListener(): 5972884208432727470 / null
D/vending (  542): [265] AssetDownloader$DownloadManagerBroadcastReceiver.installFromUri(): Calling install uri=content://downloads/download/63 src=null asset=5972884208432727470 (com.google.android.stardroid:0) [DOWNLOADING] name=Google Sky Map last=TRUE
D/MediaScannerService(  384): IMediaScannerService.scanFile: /mnt/sdcard/download/downloadfile.apk mimeType: application/vnd.android.package-archive
D/vending (  542): [265] LocalAssetDatabase.notifyListener(): 5972884208432727470 / INSTALLING
D/vending (  542): [265] VendingNotificationManager.showNotification(): Showing notification: [AssetID=5972884208432727470, NotificationID=-1611541633, Title=Google Sky Map, Message=Installing…]
I/ActivityManager(   94): Start proc com.android.defcontainer for service com.android.defcontainer/.DefaultContainerService: pid=3988 uid=10012 gids={1015, 2001}
D/dalvikvm( 3988): GC_EXPLICIT freed 736 objects / 54248 bytes in 85ms
D/VoldCmdListener(   52): asec list
I/PackageHelper( 3988): Size of container 3 MB 1535308 bytes
D/VoldCmdListener(   52): asec create smdl2tmp1 3 fat {} 10012
E/Vold    (   52): Unable to open /dev/block/loop0 (No such device or address)
E/Vold    (   52): ASEC loop device creation failed (No such device or address)
W/Vold    (   52): Returning OperationFailed - no handler for errno 6
E/PackageHelper( 3988): Failed to create secure container smdl2tmp1
E/DefContainer( 3988): Failed to create container smdl2tmp1
D/dalvikvm(   94): GC_EXPLICIT freed 17959 objects / 805760 bytes in 262ms
D/vending (  542): [17] LocalAssetDatabase.notifyListener(): 5972884208432727470 / INSTALL_FAILED
D/vending (  542): [17] VendingNotificationManager.showNotification(): Showing notification: [AssetID=5972884208432727470, NotificationID=-1611541633, Title=Google Sky Map, Message=Installation unsuccessful.]
I/vending (  542): [17] AssetDownloader$DownloadManagerBroadcastReceiver$MyPackageInstallObserver.packageInstalled(): Package install from content://downloads/download/63 failed: Unknown reason -18
D/dalvikvm(  306): GC_EXPLICIT freed 1624 objects / 85336 bytes in 257ms
E/Tethering(   94): active iface (usb0) reported as added, ignoring
D/WifiService(   94): ACTION_BATTERY_CHANGED pluggedType: 2
D/setcpu  ( 2345): Normal Profile 691200, 245760, ondemand
D/dalvikvm(  408): GC_FOR_MALLOC freed 9839 objects / 525792 bytes in 178ms

**Comment by loxK** [comment] 2010-07-06 00:50
It is a duplicate of that bug: http://github.com/loxK/android_device_htc_hero/issues#issue/8

Closing

**Closed as completed by loxK** 2010-07-06 00:50 UTC
